content_before:
  default: "<strong>Donations progression</strong>"
  type: string
content_after:
  default: ""
  type: string
progress_bar_width_value:
  default: 500
  type: integer
progress_bar_width_unit:
  default: "px"
  type: string
progress_bar_height_value:
  default: 10
  type: integer
progress_bar_height_unit:
  default: "px"
  type: string
max_value:
  default: 100
  type: integer
current_value:
  default: 0
  type: integer
progress_unit:
  default: "$"
  type: string
hide_when_full:
  default: false
  type: bool
outlet_name:
  default: "above-main-container"
  type: string
