content_before:
  default: "<strong>Donation progress bar</strong>"
  type: string
content_after:
  default: "<em>The progress bar will disappear as soon as the donation goal is met.</em>"
  type: string
progress_bar_max_width:
  default: "500px"
  type: string
progress_bar_height:
  default: "20px"
  type: string
max_value:
  default: 0
  type: integer
current_value:
  default: 0
  type: integer
currency:
  default: "$"
  type: string
hide_when_full:
  default: false
  type: bool
outlet_name:
  default: "below-site-header"
  type: string
